### ISSUE TITLE
Explorer loses list of remote workspace files when Explorer pane is hidden and reopened

### ISSUE THREAD

**Issue by SteveGuidi** [mkloubert/vscode-remote-workspace#55]
Repo steps:

1. Connect to a remote workspace (I am using SFTP)
2. Open a file from remote workspace via Explorer pane
3. Navigate to another pane, say Extensions
4. Navigate back to Explorer pane and observe that remote file tree is collapsed and won't refresh list of files.

I can only get the directory tree to refresh if I close all open files then refresh the workspace, which is not a feasible workaround.

**Comment by jmandivarapu1** [comment]
Same here

**Comment by jmandivarapu1** [comment]
is there any workaround for this?

**Comment by mkloubert** [comment]
@SteveGuidi @jmandivarapu1 @brentkelly 

**I have released a new version 0.35.0** and implemented a queue system for protocols [FTPs](https://github.com/mkloubert/vscode-remote-workspace#ftps-) and [SFTP](https://github.com/mkloubert/vscode-remote-workspace#sftp-).

I hope that this will fix that issue.

**Comment by ketsching** [comment]
@SteveGuidi 

Unfortunately not. The issue is still there in version 0.36.5

I hope you can fix that issue soon.
